version: "3"

services:

  angular:
    container_name: cliente-twohand
    build: ./cliente
    ports:
      - ${ANGULAR_PORT}:${ANGULAR_PORT}
    networks:
      - twohand

  rest:
    container_name: server-twohand
    build: ./servidor
    depends_on:
      - mongo
    ports:
      - ${REST_PORT}:${REST_PORT}
    environment:
      - DB_MONGO= ${DB_MONGO}
      - SECRET= ${SECRET}
    networks:
      - twohand

  mongo:
    container_name: twohand-mongo
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./dump/:/docker-entrypoint-initdb.d/dump/
    networks:
      - twohand

networks:
  twohand:
  prometheus:
    external: 
      name: network-log