FROM  node:16-alpine3.12

WORKDIR /usr/src/app/cliente

COPY . .

RUN npm install -g npm@8.1.2

RUN npm update

RUN npm install

EXPOSE 4200

RUN npm install -y -g @angular/cli

CMD ng serve --host 0.0.0.0